"""Tests for the shared NRIC/FIN checksum algorithm.

Two layers per series (S/T/F/G/M):

1. Fixed fixtures: hand-computed (prefix, digits, checksum) triples,
   one or two per series, that I verified by working through the
   algorithm step by step. A failure here points at a specific concrete
   input and is easy to debug.

2. Property-based via Hypothesis: for any (prefix, digits) tuple
   sampled from the legal input space, the round trip
   `is_valid_nric_fin(prefix + digits + expected_checksum(prefix, digits))`
   must return True, and substituting any other letter for the
   computed checksum must return False. This pins the algorithm against
   the entire input space, not just the chosen fixtures.

External cross-validation: spot-check a few of the fixture values
against an independent online validator (e.g. samliew.com's NRIC
validator) before relying on the implementation in production.

All fixtures are synthetic. The first-issued historical NRICs are
deliberately NOT used as test inputs; per the project's data-sensitivity
rules, real (even if deceased and publicly known) NRIC numbers stay out
of the repo.
"""

from __future__ import annotations

import string

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from presidio_sg_recognizers._checksum import (
    expected_checksum,
    is_valid_nric_fin,
)

# ---------------------------------------------------------------------------
# Layer 1: hand-verified fixed fixtures.
# Each triple is (prefix, seven-digit body, expected checksum letter).
# The checksums were computed by working the algorithm by hand for each
# entry; the comments above each line show the weighted-sum derivation
# so the value is auditable from the spec without re-running the code.
# Spot-check against an independent online validator (e.g. samliew.com's
# NRIC validator) before treating any of these as authoritative.
# ---------------------------------------------------------------------------

NRIC_VALID_FIXTURES: tuple[tuple[str, str, str], ...] = (
    # S series, no prefix offset, NRIC lookup table "JZIHGFEDCBA".
    # Worked example for S1234567:
    #   sum = 1*2 + 2*7 + 3*6 + 4*5 + 5*4 + 6*3 + 7*2 = 106
    #   106 mod 11 = 7 -> table[7] = "D"
    ("S", "1234567", "D"),
    # Worked example for S9876543:
    #   sum = 9*2 + 8*7 + 7*6 + 6*5 + 5*4 + 4*3 + 3*2 = 184
    #   184 mod 11 = 8 -> table[8] = "C"
    ("S", "9876543", "C"),
    # All zeros except last; sum = 1*2 = 2; table[2] = "I".
    ("S", "0000001", "I"),
    # T series, prefix offset +4.
    # Worked example for T1234567:
    #   sum = 106 + 4 = 110; 110 mod 11 = 0 -> table[0] = "J"
    ("T", "1234567", "J"),
    # Worked example for T0000001:
    #   sum = 2 + 4 = 6; 6 mod 11 = 6 -> table[6] = "E"
    ("T", "0000001", "E"),
)

FIN_VALID_FIXTURES: tuple[tuple[str, str, str], ...] = (
    # F, G, and M all share the FIN lookup table "XWUTRQPNMLK" and
    # differ only in prefix offset (F=0, G=4, M=3).
    #
    # F series, no prefix offset.
    # Worked example for F1234567:
    #   sum = 106; 106 mod 11 = 7 -> table[7] = "N"
    ("F", "1234567", "N"),
    # Worked example for F0000001:
    #   sum = 2; 2 mod 11 = 2 -> table[2] = "U"
    ("F", "0000001", "U"),
    # G series, prefix offset +4.
    # Worked example for G1234567:
    #   sum = 110; 110 mod 11 = 0 -> table[0] = "X"
    ("G", "1234567", "X"),
    # Worked example for G0000001:
    #   sum = 2 + 4 = 6; 6 mod 11 = 6 -> table[6] = "P"
    ("G", "0000001", "P"),
    # M series, prefix offset +3.
    # Worked example for M1234567:
    #   sum = 106 + 3 = 109; 109 mod 11 = 10 -> table[10] = "K"
    ("M", "1234567", "K"),
    # Worked example for M0000001:
    #   sum = 2 + 3 = 5; 5 mod 11 = 5 -> table[5] = "Q"
    ("M", "0000001", "Q"),
)

# Independent cross-validation samples generated by samliew.com's NRIC
# validator (https://samliew.com/singapore-nric-validator) and confirmed
# valid against an external tool. These pin the lookup tables against
# real-world output rather than self-derived computation, catching the
# class of bug where my hand-derivation and the algorithm agree but the
# underlying table assignment is wrong.
SAMLIEW_VALIDATED_SAMPLES: tuple[str, ...] = (
    "S9334391C",
    "S1855396A",
    "S3185214E",
    "T9221398B",
    "T0937406F",
    "T9625527B",
    "F7400134M",
    "F9374705N",
    "F9422491T",
    "G3918414T",
    "G1663120K",
    "G7674562K",
    "M3584791R",
    "M5111432Q",
    "M7160497N",
)


@pytest.mark.parametrize(("prefix", "digits", "expected"), NRIC_VALID_FIXTURES)
def test_nric_expected_checksum_matches_hand_verified(prefix, digits, expected):
    """`expected_checksum` returns the hand-computed letter for S/T NRICs."""
    assert expected_checksum(prefix, digits) == expected


@pytest.mark.parametrize(("prefix", "digits", "expected"), FIN_VALID_FIXTURES)
def test_fin_expected_checksum_matches_hand_verified(prefix, digits, expected):
    """`expected_checksum` returns the hand-computed letter for F/G/M FINs."""
    assert expected_checksum(prefix, digits) == expected


@pytest.mark.parametrize(("prefix", "digits", "checksum"), NRIC_VALID_FIXTURES + FIN_VALID_FIXTURES)
def test_is_valid_accepts_hand_verified_identifiers(prefix, digits, checksum):
    """`is_valid_nric_fin` accepts every hand-verified valid identifier."""
    assert is_valid_nric_fin(f"{prefix}{digits}{checksum}") is True


@pytest.mark.parametrize(
    ("prefix", "digits", "_checksum"), NRIC_VALID_FIXTURES + FIN_VALID_FIXTURES
)
def test_is_valid_rejects_wrong_checksum_letter(prefix, digits, _checksum):
    """Flipping the checksum letter to any other letter makes the input invalid."""
    correct = expected_checksum(prefix, digits)
    for wrong_letter in string.ascii_uppercase:
        if wrong_letter == correct:
            continue
        assert is_valid_nric_fin(f"{prefix}{digits}{wrong_letter}") is False


@pytest.mark.parametrize(
    "bad_input",
    [
        "",  # empty
        "S123456A",  # too short
        "S12345678A",  # too long
        "X1234567A",  # unknown prefix
        "S123456AA",  # non-digit in body
        "S1234567 ",  # trailing whitespace not stripped by the validator
        "1234567SA",  # wrong shape
    ],
)
def test_is_valid_rejects_malformed_inputs(bad_input):
    """Format-level garbage is rejected before the checksum is even computed."""
    assert is_valid_nric_fin(bad_input) is False


def test_is_valid_is_case_insensitive_on_input():
    """The validator accepts lowercase input by normalising to uppercase."""
    # S1234567D in mixed case.
    assert is_valid_nric_fin("s1234567d") is True
    assert is_valid_nric_fin("S1234567d") is True


def test_expected_checksum_raises_on_bad_prefix():
    with pytest.raises(ValueError, match="unknown prefix"):
        expected_checksum("X", "1234567")


def test_expected_checksum_raises_on_bad_digits():
    with pytest.raises(ValueError, match="exactly seven decimal"):
        expected_checksum("S", "12345")
    with pytest.raises(ValueError, match="exactly seven decimal"):
        expected_checksum("S", "12345AB")


@pytest.mark.parametrize("sample", SAMLIEW_VALIDATED_SAMPLES)
def test_samliew_validated_samples_accepted(sample):
    """Each samliew-confirmed valid identifier passes our validator."""
    assert is_valid_nric_fin(sample) is True


def test_known_invalid_m_series_rejected():
    """M1234567X was independently confirmed invalid by samliew.

    Documented here as a regression guard: an earlier implementation
    used a separate (incorrect) M-series lookup table that would have
    accepted M1234567X as valid. The corrected implementation shares
    the FIN table across F/G/M and computes M1234567K as the only
    valid form.
    """
    assert is_valid_nric_fin("M1234567X") is False
    assert is_valid_nric_fin("M1234567K") is True


# ---------------------------------------------------------------------------
# Layer 2: Hypothesis property-based round-trip tests.
# For any legal (prefix, digits) input, the algorithm is self-consistent:
# - the computed checksum letter, when appended, validates as a complete
#   identifier;
# - any other letter in the checksum position fails validation.
# Together these pin the algorithm against the entire 5 * 10^7 input
# space, far beyond what fixed fixtures could cover.
# ---------------------------------------------------------------------------

_PREFIXES = st.sampled_from(["S", "T", "F", "G", "M"])
_DIGITS_7 = st.text(alphabet=string.digits, min_size=7, max_size=7)


@given(prefix=_PREFIXES, digits=_DIGITS_7)
@settings(max_examples=500, deadline=None)
def test_constructed_identifier_validates(prefix, digits):
    """For any (prefix, digits), `prefix + digits + computed_checksum` validates."""
    checksum = expected_checksum(prefix, digits)
    assert is_valid_nric_fin(f"{prefix}{digits}{checksum}") is True


@given(
    prefix=_PREFIXES,
    digits=_DIGITS_7,
    wrong_letter=st.sampled_from(list(string.ascii_uppercase)),
)
@settings(max_examples=500, deadline=None)
def test_wrong_checksum_letter_rejected(prefix, digits, wrong_letter):
    """Any letter that is not the computed checksum fails validation."""
    correct = expected_checksum(prefix, digits)
    if wrong_letter == correct:
        return  # skip; tested elsewhere
    assert is_valid_nric_fin(f"{prefix}{digits}{wrong_letter}") is False
